version: '3'
services:
  camel:
    container_name: ${DOCKER_CONTAINER}
    build: .
    image: ${DOCKER_CONTAINER}:latest
    ports:
      - "${DOCKER_HTTP_PORT}:80"
      - "${DOCKER_HTTPS_PORT}:443"
    volumes:
      - "./data:/data"
    env_file: .env
    restart: always
